### PR TITLE
responsive ui and navbar

### PR DESCRIPTION
**Pull request by abhishekpanthee**
Enhanced responsiveness for mobile devices
Fixed Navbar  
Improved button placements and interactions
Updated several components (including Footer, Newsletter, Popular, Offers, ProductDisplay, RelatedProducts, and items)

### CODE REVIEW

**Comment by abhishekpanthee** [comment]
Please label this under hacktoberfest'24.

**Comment by imadityayadav** [comment]
> Please label this under hacktoberfest'24.

hey abhishek please add the ss of before and after
and the paths/files where you have made the commits

**Comment by abhishekpanthee** [comment]
Before --
before5
before4
before3
before7
before8
![before9 befrore10.png…]()
before2
before1

After ---
Screenshot from 2024-10-04 22-59-20
Screenshot from 2024-10-04 22-59-17
Screenshot from 2024-10-04 22-59-12
Screenshot from 2024-10-04 22-59-08
Screenshot from 2024-10-04 22-59-03
Screenshot from 2024-10-04 22-58-57
Screenshot from 2024-10-04 22-58-54
Screenshot from 2024-10-04 22-58-44

For those files I have changed I think 20 files you can see it in the files changed section

**Comment by imadityayadav** [comment]
Ohh nice work!!

**Comment by abhishekpanthee** [comment]
I really have a request please add labels of hacktoberfest and gsscoc it helps a lot and is a win-win I was worried as i didn't see that label in pr section so do review it once

**Comment by imadityayadav** [comment]
> I really have a request please add labels of hacktoberfest and gsscoc it helps a lot and is a win-win I was worried as i didn't see that label in pr section so do review it once 

Sure

**Pull request merged**
